apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq

spec:
  selector:
    matchLabels:
      app: rabbitmq

  # Pod defenition
  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management

          ports:
            - containerPort: 15672

          # Example of 'ConfigMap/Secret' files env declaration
          env:
            - name: RABBITMQ_DEFAULT_USER # Env var name
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets # Name of secret
                  key: default-user # Name of key in secret
            
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: default-password

            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: earlang-cookie

            - name: RABBITMQ_DEFAULT_VHOST # Env var name
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config # Name of ConfigMap
                  key: default-vhost # Name of key in ConfigMap

# Yaml file seperator
--- 

# External service of rabbitmq deployment
apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-service

spec:
  selector:
    app: rabbitmq
  
  ports:
    - protocol: TCP
      name: admin
      port: 15672
      targetPort: 15672

    - protocol: TCP
      name: access-port
      port: 5672
      targetPort: 5672

  type: LoadBalancer